name: Get Unity Activation File
on: [workflow_dispatch]

jobs:
  getManualActivationFile:
    name: Get Manual Activation File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Request manual activation file
        uses: game-ci/unity-activate@v4
        id: activation
        # No license needed here - this GENERATES the .alf request file

      - name: Upload activation file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: ${{ steps.activation.outputs.filePath }}
          retention-days: 1